/*
  app.js -- This creates an Express webserver with login/register/logout authentication
*/

// *********************************************************** //
//  Loading packages to support the server
// *********************************************************** //
// First we load in all of the packages we need for the server...
const createError = require("http-errors"); // to handle the server errors
const express = require("express");
const path = require("path"); // to refer to local paths
const cookieParser = require("cookie-parser"); // to handle cookies
const session = require("express-session"); // to handle sessions using cookies
const debug = require("debug")("personalapp:server");
const layouts = require("express-ejs-layouts");
const axios = require("axios")

// *********************************************************** //
//  Loading models
// *********************************************************** //
const NBA_Rating = require("./models/NBA_Rating")
const Players = require("./models/Players")

// *********************************************************** //
//  Loading JSON datasets
// *********************************************************** //
const ratings = require('./public/data/nba2k.json')


// *********************************************************** //
//  Connecting to the database
// *********************************************************** //

const mongoose = require('mongoose');
// const mongodb_URI = 'mongodb://localhost:27017/cpa02'
const mongodb_URI = 'mongodb+srv://GuangyaoD:200130dole@cpa02.sx5qy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
//const mongodb_URI = 'mongodb+srv://cs_sj:BrandeisSpr22@cluster0.kgugl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'

mongoose.connect(mongodb_URI || 'mongodb://localhost:27017/cpa02', { useNewUrlParser: true, useUnifiedTopology: true });
// fix deprecation warnings
mongoose.set('useFindAndModify', false);
mongoose.set('useCreateIndex', true);

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() { console.log("we are connected!!!") });

// *********************************************************** //
// Initializing the Express server 
// This code is run once when the app is started and it creates
// a server that respond to requests by sending responses
// *********************************************************** //
const app = express();

// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");



// this allows us to use page layout for the views 
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
    session({
        secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
        resave: false,
        saveUninitialized: false
    })
);

// *********************************************************** //
//  Defining the routes the Express server will respond to
// *********************************************************** //


// here is the code which handles all /login /signin /logout routes
const auth = require('./routes/auth');
const { deflateSync } = require("zlib");
app.use(auth)

// middleware to test is the user is logged in, and if not, send them to the login page
const isLoggedIn = (req, res, next) => {
    if (res.locals.loggedIn) {
        next()
    } else res.redirect('/login')
}

// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", isLoggedIn, (req, res, next) => {
    res.render("index");
});

/* ************************
  Loading (or reloading) the data into a collection
   ************************ */
// this route loads in the ratings into the NBA_Rating collection
// or updates the courses if it is not a new collection

app.get('/upsertDB',
    async(req, res, next) => {
        for (rates of ratings) {
            console.log(rates);
            const { full_name, rating, jersey, team, position, b_day, height, weight,
                    salary, country} = rates;
            rates.height = getNum(height);
            rates.weight = getNum(weight);
            rates.salary = getSalary(salary);
            await NBA_Rating.findOneAndUpdate({ full_name, rating, jersey, team, position,
                                                b_day, country}, rates, { upsert: true })
        }

        const num = await NBA_Rating.find({}).count();
        res.send("data uploaded: " + num)
    }
)


function getNum(data_num) {
    // separate out a height and weight 
    // a height: "6-7 / 2.01" => "6-7"
    // a weight: "225 lbs. / 102.1 kg." => 225
    if (data_num.length == 0){
        return "";
    } 
    const myArray = data_num.split(" ");
    return myArray[0]
}

function getSalary(salary) {
    // separate out a the dollar sign and the number
    // a salary: "$32742000" => "32742000"
    if (salary.length == 0){
        return "";
    }
    return salary.slice(1);
}

app.get("/search", isLoggedIn, 
    (req, res, next) => {
        res.render("search");
});

app.post('/players/byPlayer',
    // show list of courses in a given subject
    async(req, res, next) => {
        const name = req.body.name;
        const players = await NBA_Rating.find({full_name: {'$regex': name, $options:'i'}}).sort({rating: -1})
        res.locals.players = players
        res.render("playerlist")
    }
)

app.post('/players/byRating',
    // show list of courses in a given subject
    async(req, res, next) => {
        const rating = req.body.rating;
        const players = await NBA_Rating.find({rating: rating}).sort({full_name: -1})
        res.locals.players = players
        res.render("playerlist")
    }
)

app.post('/players/byRange',
    // show list of courses in a given subject
    async(req, res, next) => {
        const range = req.body.range;
        const players = await NBA_Rating.find({rating: {$gt:range}}).sort({rating: 1})
        res.locals.players = players
        res.render("playerlist")
    }
)

app.post('/players/byTeam',
    // show list of courses in a given subject
    async(req, res, next) => {
        const team = req.body.team;
        const players = await NBA_Rating.find({team: {'$regex': team, $options:'i'}}).sort({rating: -1})
        res.locals.players = players
        res.render("playerlist")
    }
)

app.get('/teams/:team_name',
    isLoggedIn, 
    // show list of players in a given team
    async(req, res, next) => {
        const {team_name} = req.params;
        const players = await NBA_Rating.find({team: {'$regex': team_name, $options:'i'}}).sort({rating: -1})
        res.locals.players = players
        res.render("playerlist")
    }
)

app.get('/players/:name/:team/:jersey_num',
    // show all info about a player given its name, team, and jersey number
    async(req, res, next) => {
        const {name, team, jersey_num}= req.params;
        jersey_str = "#" + jersey_num.toString()
        const player = await NBA_Rating.findOne({full_name: {'$regex': name, $options:'i'}, team: team, jersey: jersey_str})
        res.locals.player=player
        res.render('player')    
    }
)

app.use(isLoggedIn)

app.get('/addPlayer/:ratingId',
    // add a course to the user's schedule
    async(req, res, next) => {
        try {
            const ratingId = req.params.ratingId
            const userId = res.locals.user._id
                // check to make sure it's not already loaded
            const lookup = await Players.find({ ratingId, userId })
            if (lookup.length == 0) {
                const players = new Players({ ratingId, userId })
                await players.save()
            }
            res.redirect('/players/show')
        } catch (e) {
            next(e)
        }
    })

app.get('/players/show',
    // show the current user's schedule
    async(req, res, next) => {
        try {
            const userId = res.locals.user._id;
            const ratingIds = (await Players.find({ userId })).map(x => x.ratingId)
            res.locals.players = await NBA_Rating.find({ _id: { $in: ratingIds } })
            res.render('schedule')
        } catch (e) {
            next(e)
        }
    }
)

app.get('/players/remove/:ratingId',
    // remove a course from the user's schedule
    async(req, res, next) => {
        try {  
            await Players.deleteOne({
                userId: res.locals.user._id,
                ratingId: req.params.ratingId
            })
            res.redirect('/players/show')

        } catch (e) {
            next(e)
        }
    }
)

// here we catch 404 errors and forward to error handler
app.use(function(req, res, next) {
    next(createError(404));
});

// this processes any errors generated by the previous routes
// notice that the function has four parameters which is how Express indicates it is an error handler
app.use(function(err, req, res, next) {
    // set locals, only providing error in development
    res.locals.message = err.message;
    res.locals.error = req.app.get("env") === "development" ? err : {};
    // render the error page
    res.status(err.status || 500);
    res.render("error");
});


// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = "8000";
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const server = http.createServer(app);

server.listen(port);

function onListening() {
    var addr = server.address();
    var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
    debug("Listening on " + bind);
}

function onError(error) {
    if (error.syscall !== "listen") {
        throw error;
    }

    var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

    // handle specific listen errors with friendly messages
    switch (error.code) {
        case "EACCES":
            console.error(bind + " requires elevated privileges");
            process.exit(1);
            break;
        case "EADDRINUSE":
            console.error(bind + " is already in use");
            process.exit(1);
            break;
        default:
            throw error;
    }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;